---
name: ExtendedSplashPotion
version: 1.0.2
main: Nerahikada\ExtendedSplashPotion\Main
api: 4.5.0
src-namespace-prefix: Nerahikada\ExtendedSplashPotion
website: https://github.com/Nerahikada/ExtendedSplashPotion
author: Nerahikada
...
